import { AlertCircle, Inbox, LoaderCircle } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"

export function PageContainer({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <div className={`mx-auto w-full max-w-7xl px-5 py-10 sm:px-8 lg:py-14 ${className}`}>{children}</div> }
export function PageHeader({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description?: string; action?: React.ReactNode }) { return <div className="mb-8 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div>{eyebrow && <p className="mb-2 text-xs font-semibold uppercase tracking-[0.18em] text-primary">{eyebrow}</p>}<h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">{title}</h1>{description && <p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground sm:text-base">{description}</p>}</div>{action}</div> }
export function SectionHeader({ title, description, action }: { title: string; description?: string; action?: React.ReactNode }) { return <div className="mb-4 flex items-end justify-between gap-4"><div><h2 className="text-lg font-semibold tracking-tight">{title}</h2>{description && <p className="mt-1 text-sm text-muted-foreground">{description}</p>}</div>{action}</div> }
export function EmptyState({ title, description, action }: { title: string; description: string; action?: React.ReactNode }) { return <Card><CardContent className="flex min-h-48 flex-col items-center justify-center px-6 text-center"><Inbox className="mb-3 size-8 text-muted-foreground" /><h3 className="font-medium">{title}</h3><p className="mt-2 max-w-sm text-sm leading-6 text-muted-foreground">{description}</p>{action && <div className="mt-5">{action}</div>}</CardContent></Card> }
export function LoadingState() { return <Card><CardContent className="flex min-h-48 items-center justify-center"><LoaderCircle className="size-6 animate-spin text-primary" /></CardContent></Card> }
export function ErrorState({ message = "Something went wrong while loading this view." }: { message?: string }) { return <Card><CardContent className="flex min-h-48 flex-col items-center justify-center text-center"><AlertCircle className="mb-3 size-8 text-destructive" /><p className="text-sm text-muted-foreground">{message}</p><Button className="mt-4" variant="outline" onClick={() => window.location.reload()}>Try again</Button></CardContent></Card> }
export function StatusBadge({ status }: { status: string }) { const tone = status === "Active" || status === "Open" || status === "Accepted" || status === "Completed" ? "bg-emerald-400/10 text-emerald-300" : status === "Rejected" || status === "Closed" ? "bg-destructive/10 text-destructive" : "bg-amber-300/10 text-amber-200"; return <span className={`inline-flex items-center rounded-full px-2.5 py-1 text-xs font-medium ${tone}`}><span aria-hidden="true" className="mr-1.5 size-1.5 rounded-full bg-current" />{status}</span> }