"use client"
import Link from "next/link"
import { ArrowRight, BriefcaseBusiness, FileText, MessageSquare, Plus, Sparkles, WalletCards } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { PageContainer, SectionHeader, StatusBadge } from "@/components/shared/page-primitives"
import { JobCard } from "@/components/jobs/job-card"
import { contracts, jobs, proposals } from "@/lib/mock-data"

const stats = [{ label: "Active projects", value: "03", icon: BriefcaseBusiness }, { label: "Open proposals", value: "08", icon: FileText }, { label: "Unread messages", value: "04", icon: MessageSquare }, { label: "This month", value: "$4,280", icon: WalletCards }]
export function DashboardContent({ role = "client" }: { role?: "client" | "freelancer" }) { return <PageContainer><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="inline-flex items-center gap-2 text-sm text-primary"><Sparkles className="size-4" />{role === "client" ? "Client workspace" : "Freelancer workspace"}</p><h1 className="mt-3 text-3xl font-semibold tracking-tight">Good morning, Jordan.</h1><p className="mt-2 text-sm text-muted-foreground">Here is a clear view of what needs your attention today.</p></div><Button asChild><Link href={role === "client" ? "/dashboard/client/jobs/new" : "/jobs"}><Plus />{role === "client" ? "Post a job" : "Find work"}</Link></Button></div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{stats.map((stat) => { const Icon = stat.icon; return <Card key={stat.label}><CardContent className="p-5"><div className="flex items-center justify-between"><p className="text-sm text-muted-foreground">{stat.label}</p><Icon className="size-4 text-primary" /></div><p className="mt-4 text-2xl font-semibold">{stat.value}</p></CardContent></Card> })}</div><div className="mt-10 grid gap-8 lg:grid-cols-[1.2fr_.8fr]"><div><SectionHeader title={role === "client" ? "Recent job activity" : "Recommended for you"} description={role === "client" ? "The latest movement across your projects." : "Projects aligned with your skills and availability."} action={<Link className="text-sm text-primary" href="/jobs">View all <ArrowRight className="ml-1 inline size-3.5" /></Link>} /><div className="grid gap-4">{jobs.slice(0, 2).map((job) => <JobCard job={job} key={job.id} />)}</div></div><div><SectionHeader title="Quick actions" /><div className="grid gap-3"><Link className="rounded-xl border border-border bg-card p-4 transition-colors hover:border-primary/50" href="/dashboard/messages"><p className="font-medium">Open your inbox</p><p className="mt-1 text-sm text-muted-foreground">4 conversations need a reply.</p></Link><Link className="rounded-xl border border-border bg-card p-4 transition-colors hover:border-primary/50" href="/dashboard/contracts"><p className="font-medium">Review active work</p><p className="mt-1 text-sm text-muted-foreground">{contracts.filter((contract) => contract.status === "Active").length} contracts are in progress.</p></Link><Link className="rounded-xl border border-border bg-card p-4 transition-colors hover:border-primary/50" href="/dashboard/proposals"><p className="font-medium">Review proposals</p><p className="mt-1 text-sm text-muted-foreground">{proposals.length} mock proposals waiting.</p></Link></div></div></div></PageContainer> }

export function DashboardContracts() { return <PageContainer><SectionHeader title="Active contracts" description="Keep the important details visible as work moves forward." /><div className="grid gap-4 md:grid-cols-2">{contracts.map((contract) => <Card key={contract.id}><CardHeader><div className="flex items-start justify-between gap-4"><div><CardTitle>{contract.title}</CardTitle><p className="mt-1 text-sm text-muted-foreground">with {contract.otherParty}</p></div><StatusBadge status={contract.status} /></div></CardHeader><CardContent><div className="flex justify-between text-sm"><span className="text-muted-foreground">{contract.budget} · started {contract.startDate}</span><span>{contract.progress}%</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${contract.progress}%` }} /></div><Button asChild className="mt-5" size="sm" variant="outline"><Link href={`/dashboard/contracts/${contract.id}`}>View contract <ArrowRight /></Link></Button></CardContent></Card>)}</div></PageContainer> }