"use client"
import Link from "next/link"
import { useState } from "react"
import { ArrowRight, Check, Search, Trash2 } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { JobCard } from "@/components/jobs/job-card"
import { EmptyState, PageContainer, PageHeader, StatusBadge } from "@/components/shared/page-primitives"
import { getFreelancer, getJob, jobs, proposals } from "@/lib/mock-data"

export function SavedJobsPage() { const [saved, setSaved] = useState(jobs.slice(0, 3)); return <PageContainer><PageHeader eyebrow="Freelancer workspace" title="Saved jobs" description="Keep the opportunities worth returning to close at hand." />{saved.length ? <div className="grid gap-4">{saved.map((job) => <div className="relative" key={job.id}><JobCard job={job} /><Button aria-label={`Remove ${job.title} from saved jobs`} className="absolute right-4 top-4" onClick={() => setSaved(saved.filter((item) => item.id !== job.id))} size="icon-sm" variant="ghost"><Trash2 /></Button></div>)}</div> : <EmptyState title="Your saved jobs are waiting" description="Save interesting opportunities while you browse the marketplace." action={<Button asChild><Link href="/jobs">Browse jobs</Link></Button>} />}</PageContainer> }
export function ProposalsPage() { const [filter, setFilter] = useState("All"); const visible = proposals.filter((proposal) => filter === "All" || proposal.status === filter); return <PageContainer><PageHeader eyebrow="Freelancer workspace" title="My proposals" description="Track every conversation from first pitch to signed work." /><div className="mb-6 flex flex-wrap gap-2">{["All", "Pending", "Shortlisted", "Accepted", "Rejected"].map((item) => <Button key={item} onClick={() => setFilter(item)} size="sm" variant={filter === item ? "default" : "outline"}>{item}</Button>)}</div><div className="space-y-3">{visible.length ? visible.map((proposal) => { const job = getJob(proposal.jobId); return <Card key={proposal.id}><CardContent className="flex flex-col justify-between gap-5 p-5 sm:flex-row sm:items-center"><div><StatusBadge status={proposal.status} /><h2 className="mt-3 font-medium">{job?.title}</h2><p className="mt-1 text-sm text-muted-foreground">Submitted {proposal.submitted} · {proposal.budget} · {proposal.delivery}</p></div><div className="flex gap-2"><Button asChild size="sm" variant="outline"><Link href={`/jobs/${proposal.jobId}`}>View job <ArrowRight /></Link></Button><Button size="sm" variant="ghost">View proposal</Button></div></CardContent></Card> }) : <EmptyState title="No proposals in this view" description="Try another status filter or explore new jobs." />}</div></PageContainer> }
export function NewJobPage() { const [saved, setSaved] = useState(false); return <PageContainer><PageHeader eyebrow="Client workspace" title="Post a new job" description="Give the right freelancer enough context to do their best work." /><Card><CardContent className="space-y-6 p-6 sm:p-8"><div><label className="text-sm font-medium" htmlFor="title">Job title</label><Input className="mt-2" id="title" placeholder="e.g. Build a brand system for a climate startup" /></div><div><label className="text-sm font-medium" htmlFor="description">Description</label><Textarea className="mt-2 min-h-36" id="description" placeholder="What are you trying to make, and what does success look like?" /></div><div className="grid gap-5 sm:grid-cols-2"><div><label className="text-sm font-medium" htmlFor="category">Category</label><select className="mt-2 h-9 w-full rounded-lg border border-input bg-background px-3 text-sm" id="category"><option>Design & Creative</option><option>Programming & Tech</option><option>Writing & Content</option><option>Marketing</option></select></div><div><label className="text-sm font-medium" htmlFor="duration">Project duration</label><select className="mt-2 h-9 w-full rounded-lg border border-input bg-background px-3 text-sm" id="duration"><option>1 to 2 weeks</option><option>3 to 5 weeks</option><option>1 to 3 months</option></select></div></div><div className="grid gap-5 sm:grid-cols-2"><div><label className="text-sm font-medium" htmlFor="min-budget">Minimum budget</label><Input className="mt-2" id="min-budget" placeholder="$1,000" /></div><div><label className="text-sm font-medium" htmlFor="max-budget">Maximum budget</label><Input className="mt-2" id="max-budget" placeholder="$2,500" /></div></div><div><label className="text-sm font-medium" htmlFor="skills">Required skills</label><Input className="mt-2" id="skills" placeholder="Figma, brand strategy, research" /></div><div className="flex flex-wrap justify-end gap-3 border-t border-border pt-6"><Button variant="outline">Cancel</Button><Button onClick={() => setSaved(true)} variant="secondary">{saved ? "Draft saved" : "Save draft"}</Button><Button onClick={() => setSaved(true)}>{saved ? <><Check />Preview ready</> : "Preview job"}</Button></div>{saved && <p className="text-right text-sm text-emerald-300">This is a local mock interaction. Nothing has been published.</p>}</CardContent></Card></PageContainer> }
export function ReceivedProposalsPage() { return <PageContainer><PageHeader eyebrow="Client workspace" title="Received proposals" description="Review the people who want to help move your projects forward." /><div className="space-y-4">{proposals.map((proposal) => { const freelancer = getFreelancer(proposal.freelancerId); const job = getJob(proposal.jobId); return <Card key={proposal.id}><CardHeader><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><p className="text-xs text-primary">For {job?.title}</p><CardTitle className="mt-1">{freelancer?.name}</CardTitle><p className="mt-1 text-sm text-muted-foreground">{freelancer?.title} · {freelancer?.rating} rating</p></div><StatusBadge status={proposal.status} /></div></CardHeader><CardContent><p className="text-sm leading-6 text-muted-foreground">{proposal.coverLetter}</p><div className="mt-5 flex flex-wrap items-center justify-between gap-3"><p className="text-sm font-medium">{proposal.budget} · delivers in {proposal.delivery}</p><div className="flex gap-2"><Button size="sm" variant="outline">View proposal</Button><Button size="sm">Shortlist</Button></div></div></CardContent></Card> })}</div></PageContainer> }

export function MessagesPage() { const [message, setMessage] = useState(""); const [sent, setSent] = useState<string[]>([]); return <PageContainer><PageHeader eyebrow="Workspace" title="Messages" description="Keep project conversations clear, useful, and close to the work." /><div className="grid min-h-[560px] overflow-hidden rounded-xl border border-border bg-card lg:grid-cols-[280px_1fr]"><aside className="border-b border-border p-4 lg:border-b-0 lg:border-r"><div className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input className="pl-9" placeholder="Search conversations" /></div><div className="mt-4 space-y-2">{["Maya Chen", "Ravi Patel", "Northstar Labs"].map((name, index) => <button className={`w-full rounded-lg p-3 text-left ${index === 0 ? "bg-muted" : "hover:bg-muted/60"}`} key={name} type="button"><p className="text-sm font-medium">{name}</p><p className="mt-1 truncate text-xs text-muted-foreground">{index === 0 ? "The latest concept is ready for review" : "Thanks, that sounds good."}</p></button>)}</div></aside><section className="flex min-h-[500px] flex-col"><div className="border-b border-border p-5"><p className="font-medium">Maya Chen</p><p className="mt-1 text-xs text-muted-foreground">Atlas product redesign</p></div><div className="flex-1 space-y-4 p-5"><div className="max-w-md rounded-2xl rounded-tl-sm bg-muted p-4 text-sm leading-6">The latest concept is ready for review. I focused the first pass on the hierarchy we discussed.</div>{sent.map((item) => <div className="ml-auto max-w-md rounded-2xl rounded-tr-sm bg-primary p-4 text-sm leading-6 text-primary-foreground" key={item}>{item}</div>)}</div><form className="flex gap-2 border-t border-border p-4" onSubmit={(event) => { event.preventDefault(); if (message.trim()) { setSent([...sent, message.trim()]); setMessage("") } }}><Input aria-label="Message" onChange={(event) => setMessage(event.target.value)} placeholder="Write a message..." value={message} /><Button type="submit">Send</Button></form></section></div></PageContainer> }