import Link from "next/link"
import { ArrowRight, CheckCircle2, FileText, Heart, Users, WalletCards } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { JobCard } from "@/components/jobs/job-card"
import { PageContainer, PageHeader, SectionHeader, StatusBadge } from "@/components/shared/page-primitives"
import { contracts, freelancers, jobs, proposals } from "@/lib/mock-data"

export function FreelancerDashboard() {
  return <PageContainer><PageHeader eyebrow="Freelancer workspace" title="Good morning, Jordan." description="A focused view of your opportunities, proposals, and active work." action={<Button asChild><Link href="/jobs">Find work <ArrowRight /></Link></Button>} /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[{ label: "Submitted proposals", value: proposals.length, icon: FileText }, { label: "Active contracts", value: contracts.filter((item) => item.role === "freelancer" && item.status === "Active").length, icon: CheckCircle2 }, { label: "Saved jobs", value: 3, icon: Heart }, { label: "Earnings placeholder", value: "$4,280", icon: WalletCards }].map((stat) => { const Icon = stat.icon; return <Card key={stat.label}><CardContent className="p-5"><Icon className="size-4 text-primary" /><p className="mt-4 text-2xl font-semibold">{stat.value}</p><p className="mt-1 text-sm text-muted-foreground">{stat.label}</p></CardContent></Card> })}</div><div className="mt-10 grid gap-8 lg:grid-cols-[1fr_320px]"><div><SectionHeader title="Recommended jobs" description="Based on your skills and availability." /><div className="grid gap-4">{jobs.slice(0, 2).map((job) => <JobCard job={job} key={job.id} />)}</div></div><div className="space-y-5"><Card><CardContent className="p-5"><div className="flex items-center justify-between"><p className="font-medium">Profile completion</p><span className="text-sm text-primary">78%</span></div><div className="mt-4 h-2 rounded-full bg-muted"><div className="h-full w-[78%] rounded-full bg-primary" /></div><p className="mt-3 text-sm text-muted-foreground">Add one portfolio project to make your profile stronger.</p><Button asChild className="mt-4" size="sm" variant="outline"><Link href="/dashboard/profile">Complete profile</Link></Button></CardContent></Card><Card><CardContent className="p-5"><p className="font-medium">Proposal pulse</p>{proposals.map((proposal) => <div className="mt-4 flex items-center justify-between gap-3" key={proposal.id}><span className="truncate text-sm text-muted-foreground">{proposal.budget}</span><StatusBadge status={proposal.status} /></div>)}<Button asChild className="mt-5" size="sm" variant="ghost"><Link href="/dashboard/freelancer/proposals">View proposals <ArrowRight /></Link></Button></CardContent></Card></div></div></PageContainer>
}

export function ClientDashboard() {
  return <PageContainer><PageHeader eyebrow="Client workspace" title="Good morning, Jordan." description="Keep your hiring pipeline, active work, and next decisions in view." action={<Button asChild><Link href="/dashboard/client/jobs/new">Post a job <ArrowRight /></Link></Button>} /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[{ label: "Posted jobs", value: 18, icon: FileText }, { label: "Active contracts", value: 3, icon: CheckCircle2 }, { label: "Received proposals", value: proposals.length, icon: Users }, { label: "Total spent", value: "$48.6k", icon: WalletCards }].map((stat) => { const Icon = stat.icon; return <Card key={stat.label}><CardContent className="p-5"><Icon className="size-4 text-primary" /><p className="mt-4 text-2xl font-semibold">{stat.value}</p><p className="mt-1 text-sm text-muted-foreground">{stat.label}</p></CardContent></Card> })}</div><div className="mt-10 grid gap-8 lg:grid-cols-[1fr_320px]"><div><SectionHeader title="Recent job activity" description="Your latest briefs and their current momentum." /><div className="grid gap-4">{jobs.slice(0, 2).map((job) => <JobCard job={job} key={job.id} />)}</div></div><div className="space-y-5"><Card><CardContent className="p-5"><p className="font-medium">Recommended freelancers</p>{freelancers.map((freelancer) => <Link className="mt-4 flex items-center gap-3" href={`/freelancers/${freelancer.id}`} key={freelancer.id}><span className="flex size-9 items-center justify-center rounded-lg bg-primary/15 text-xs font-semibold text-primary">{freelancer.initials}</span><span><span className="block text-sm font-medium">{freelancer.name}</span><span className="block text-xs text-muted-foreground">{freelancer.title}</span></span></Link>)}</CardContent></Card><Card><CardContent className="p-5"><p className="font-medium">Hiring pipeline</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Two proposals are ready for review, and one contract milestone needs your attention.</p><Button asChild className="mt-4" size="sm" variant="outline"><Link href="/dashboard/client/proposals">Review proposals</Link></Button></CardContent></Card></div></div></PageContainer>
}
