import Link from "next/link"
import { ArrowUpRight, Menu, Sparkles } from "lucide-react"
import { Button } from "@/components/ui/button"

export function PublicNavbar() {
  return <header className="border-b border-border/70 bg-background/90 backdrop-blur"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 sm:px-8"><Link className="flex items-center gap-2 text-sm font-semibold tracking-tight" href="/"><span className="flex size-8 items-center justify-center rounded-lg bg-primary text-primary-foreground"><Sparkles className="size-4" /></span>freelancex</Link><nav className="hidden items-center gap-7 text-sm text-muted-foreground md:flex"><Link className="hover:text-foreground" href="/jobs">Find work</Link><Link className="hover:text-foreground" href="/freelancers/maya-chen">Hire talent</Link><Link className="hover:text-foreground" href="/categories">Categories</Link><Link className="hover:text-foreground" href="/how-it-works">How it works</Link></nav><div className="flex items-center gap-2"><Link className="hidden text-sm text-muted-foreground hover:text-foreground sm:block" href="/sign-in">Sign in</Link><Button asChild size="sm"><Link href="/sign-up">Join FreelanceX <ArrowUpRight /></Link></Button><Button aria-label="Open public navigation" className="md:hidden" size="icon" variant="ghost"><Menu /></Button></div></div></header>
}
export function PublicFooter() {
  return <footer className="border-t border-border/70 bg-card/40"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-12 sm:px-8 md:grid-cols-[1.4fr_repeat(3,1fr)]"><div><Link className="font-semibold" href="/">freelancex</Link><p className="mt-3 max-w-xs text-sm leading-6 text-muted-foreground">The calm, capable way to find the people who make good work happen.</p></div><div><p className="text-sm font-medium">Marketplace</p><div className="mt-4 space-y-3 text-sm text-muted-foreground"><Link className="block hover:text-foreground" href="/jobs">Browse jobs</Link><Link className="block hover:text-foreground" href="/freelancers/maya-chen">Find freelancers</Link><Link className="block hover:text-foreground" href="/categories">Categories</Link></div></div><div><p className="text-sm font-medium">Company</p><div className="mt-4 space-y-3 text-sm text-muted-foreground"><Link className="block hover:text-foreground" href="/about">About</Link><Link className="block hover:text-foreground" href="/how-it-works">How it works</Link><Link className="block hover:text-foreground" href="/contact">Contact</Link></div></div><div><p className="text-sm font-medium">Legal</p><div className="mt-4 space-y-3 text-sm text-muted-foreground"><Link className="block hover:text-foreground" href="/privacy">Privacy</Link><Link className="block hover:text-foreground" href="/terms">Terms</Link><Link className="block hover:text-foreground" href="/help">Help center</Link></div></div></div><div className="mx-auto max-w-7xl border-t border-border/70 px-5 py-5 text-xs text-muted-foreground sm:px-8">© 2026 FreelanceX. Built for better work.</div></footer>
}
export function PublicShell({ children }: { children: React.ReactNode }) { return <div className="min-h-screen bg-background"><PublicNavbar />{children}<PublicFooter /></div> }